/* Generated by tools/build.mjs — do not edit by hand.
   CACHE is a hash of the precached bytes, so any content change invalidates
   the old cache automatically. */

var CACHE = 'games-e401d0731a4f';

var PRECACHE = [
  "./",
  "2048.html",
  "assets/fonts/inter-latin-ext.woff2",
  "assets/fonts/inter-latin.woff2",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/favicon-32.png",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon.svg",
  "chat.html",
  "css/2048.css",
  "css/hangman.css",
  "css/hub.css",
  "css/kakuro.css",
  "css/killer.css",
  "css/mastermind.css",
  "css/minesweeper.css",
  "css/nonogram.css",
  "css/solitaire.css",
  "css/sudoku.css",
  "css/theme.css",
  "css/ui.css",
  "css/wordle.css",
  "css/wordsearch.css",
  "guesses-en.json",
  "guesses-sl.json",
  "hangman.html",
  "index.html",
  "js/core/boot.js",
  "js/core/generate.js",
  "js/core/prefs.js",
  "js/core/rng.js",
  "js/core/scoring.js",
  "js/core/session.js",
  "js/core/share.js",
  "js/core/stats.js",
  "js/core/statsview.js",
  "js/core/store.js",
  "js/core/ui.js",
  "js/core/words.js",
  "js/games/2048.js",
  "js/games/hangman.js",
  "js/games/kakuro.js",
  "js/games/killer.js",
  "js/games/mastermind.js",
  "js/games/minesweeper.js",
  "js/games/nonogram.js",
  "js/games/solitaire.js",
  "js/games/sudoku.js",
  "js/games/wordle.js",
  "js/games/wordsearch.js",
  "js/gen/kakuro.js",
  "js/gen/killer.js",
  "js/gen/minesweeper.js",
  "js/gen/nonogram.js",
  "js/gen/sudoku.js",
  "js/gen/wordsearch.js",
  "js/gen/worker.js",
  "js/hub.js",
  "kakuro.html",
  "killer.html",
  "manifest.webmanifest",
  "mastermind.html",
  "minesweeper.html",
  "nonogram.html",
  "offline.html",
  "solitaire.html",
  "sudoku.html",
  "wordle.html",
  "words-en.json",
  "words-sl.json",
  "wordsearch.html"
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE).then(function (cache) {
      // Add files individually. cache.addAll is atomic, so one 404 would
      // reject the whole install and leave the app with no offline support
      // at all; a single missing file should not cost us everything.
      return Promise.all(PRECACHE.map(function (url) {
        return cache.add(new Request(url, { cache: 'reload' })).catch(function () {
          return null;
        });
      }));
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (names) {
      return Promise.all(names.map(function (name) {
        if (name !== CACHE) return caches.delete(name);
        return null;
      }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener('message', function (event) {
  if (event.data === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', function (event) {
  var request = event.request;
  if (request.method !== 'GET') return;

  var url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: try the network first so a reload picks up a new build,
  // fall back to the cached page, then to the offline placeholder. Without
  // the fallback an offline navigation to an uncached URL is a browser error
  // page, which looks like the whole app is broken.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request).catch(function () {
        return caches.match(request).then(function (hit) {
          return hit || caches.match('index.html') || caches.match('offline.html');
        });
      })
    );
    return;
  }

  // Everything else is immutable for the life of a cache version.
  event.respondWith(
    caches.match(request).then(function (hit) {
      if (hit) return hit;
      return fetch(request).then(function (response) {
        if (response && response.ok && response.type === 'basic') {
          var copy = response.clone();
          caches.open(CACHE).then(function (cache) { cache.put(request, copy); });
        }
        return response;
      });
    })
  );
});
